[/]
app-menu-ellipsize-mode='middle'
enable-titlebar-actions=true
greyscale-tray-icons=false
hide-activities-button='always'
hide-app-menu-icon=true
hide-window-titlebars='always'
notifications-position='center'
show-appmenu-button=true
show-desktop-name=false
show-legacy-tray=false
show-window-buttons='never'
