---
- name: Install tmux
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - tmux

- name: Install byobu
  yaourt: name={{item}}
          state=present
  with_items:
    - byobu
