---
- name: Install choose
  community.general.homebrew:
    name: choose-gui

- name: Create local bin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Deploy project launcher script
  ansible.builtin.copy:
    src: files/bin/project-launcher
    dest: "{{ ansible_env.HOME }}/.local/bin/project-launcher"
    mode: "+x"
