#!/bin/bash
(
    flock -x -w 0.5 200 || exit 1

    tempfile=/tmp/blurlock.tmp.png
    resolution=`xdpyinfo | grep dimensions | awk '{print $2}'`
    ffmpeg -f x11grab -video_size $resolution -i $DISPLAY -filter_complex "boxblur=10:1" -vframes 1 $tempfile -loglevel quiet
    i3lock -nxi $tempfile
    rm $tempfile

) 200>/tmp/blurlock.lock
