#!/bin/bash
(
    flock -x -w 2 200 || exit 1

    import -window root /tmp/blurlock.raw.png
    convert /tmp/blurlock.raw.png -filter point -resize 2% -resize 5000% /tmp/blurlock.png
    rm /tmp/blurlock.raw.png
    i3lock -nxi /tmp/blurlock.png

) 200>/tmp/blurlock.lock
