---
- name: Install ulauncher and ydotool
  become: yes
  dnf:
    name:
      - ulauncher
      - ydotool

- name: Widen ulauncher window
  become: yes
  community.general.xml:
    path: /usr/share/ulauncher/ui/UlauncherWindow.ui
    xpath: //*[@id="ulauncher_window"]/property[@name="width_request"]
    value: "1004"

- name: Widen ulauncher names
  become: yes
  community.general.xml:
    path: /usr/share/ulauncher/ui/result_item.ui
    xpath: //*[@id="name_wrapper"]/property[@name="width-request"]
    value: "810"

- name: Make sure extensions directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/ulauncher/extensions"
    state: directory

- name: Install projects extension
  copy:
    src: files/ulauncher-projects
    dest: "{{ ansible_env.HOME }}/.local/share/ulauncher/extensions"

- name: Install rbw extension
  copy:
    src: files/ulauncher-rbw
    dest: "{{ ansible_env.HOME }}/.local/share/ulauncher/extensions"

- name: Install ykman extension
  copy:
    src: files/ulauncher-ykman
    dest: "{{ ansible_env.HOME }}/.local/share/ulauncher/extensions"

- name: Disable ydotoold systemd service
  systemd:
    name: ydotool
    scope: system
    state: stopped
    enabled: no

- name: Create autostart directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory

- name: Create uinput-users group
  become: yes
  group:
    name: uinput-users
    state: present

- name: Add user to uinput-users group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - uinput-users
    append: yes

- name: Add udev rule for /dev/uinput access
  become: yes
  lineinfile:
    path: /etc/udev/rules.d/80-uinput.rules
    line: "KERNEL==\"uinput\", GROUP=\"uinput-users\", MODE=\"0660\", OPTIONS+=\"static_node=uinput\""
    create: yes
  register: uinput_udev_rule

- name: Add autostart desktop file for ydotoold
  copy:
    src: files/ydotoold.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/ydotoold.desktop"
