---
- hosts: all
  roles:
    - core
    - gnome
    - fonts
    - terminal
    # - nodejs
    # - python
    # - emacs
    # - vim
    # - yubikey

    # keep completions last since they depend on programs to generate
    # - completions
