---
- hosts: all
  roles:
    - { name: terminal, tags: [terminal] }
    - { name: fonts, tags: [fonts] }
    - { name: rectangle, tags: [rectangle, wm] }
    - { name: vim, tags: [vim] }
    - { name: emacs, tags: [emacs] }
    - { name: github, tags: [github] }
    - { name: choose, tags: [choose] }
    - { name: graphite, tags: [graphite] }

    # keep completions last since they depend on programs to generate
    - { name: completions, tags: [completions] }
