---
- name: Provision dev system
  hosts: all
  roles:
    - base
    - git
    - zsh
    - byobu
    - emacs
    - vim
    - python
    - node
    - postgres
    - mysql
    - heroku
    - aws
    - ngrok

- name: Configure dev environment
  hosts: all
  roles:
    - dotfiles

  vars_prompt:
    - name: "git_name"
      prompt: "Git user.name:"
    - name: "git_email"
      prompt: "Git user.email:"
