---
- name: Provision dev system
  hosts: all
  tasks:
    - group_by: key=ubuntu_release_{{ansible_distribution_release}}
  roles:
    - base
    - git
    - zsh
    - byobu
    - vim
    - python
    - node
    - postgres
    - mysql
    - heroku
    - aws
    - ngrok

- hosts: ubuntu_release_trusty
  roles:
    - emacs-source

- hosts: ubuntu_release_wily
  roles:
    - emacs

- name: Configure dev environment
  hosts: all
  roles:
    - dotfiles

  vars_prompt:
    - name: "git_name"
      prompt: "Git user.name:"
    - name: "git_email"
      prompt: "Git user.email:"
