---
- name: Sync oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.oh-my-zsh"

- name: Sync spacemacs
  git: repo=https://github.com/syl20bnr/spacemacs.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.emacs.d"

- name: Sync dotfiles repo over SSH
  git: repo=git@github.com:alanctkc/dotfiles.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.config/dotfiles"
  register: ssh_clone
  ignore_errors: True  # will fail with local changes

- name: Sync dotfiles repo over HTTPS
  git: repo=https://github.com/alanctkc/dotfiles.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.config/dotfiles"
  when: ssh_clone|failed
  ignore_errors: True  # will fail with local changes

- name: Link all dotfiles
  command: ./dotme.sh
  args:
    chdir: "{{ansible_env.HOME}}/.config/dotfiles"
    creates: "{{ansible_env.HOME}}/.dotted"
