---
- name: Sync oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.oh-my-zsh"

- name: Sync spacemacs
  git: repo=https://github.com/syl20bnr/spacemacs.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.emacs.d"

- name: Link all dotfiles
  command: ./dotme.sh
  args:
    chdir: "{{ansible_env.HOME}}/.config/dotfiles"
    creates: "{{ansible_env.HOME}}/.dotted"

- name: Remove default user dotfile extensions
  file: path={{item}}
        state=absent
  with_items:
    - "{{ansible_env.HOME}}/.extend.bashrc"
    - "{{ansible_env.HOME}}/.extend.Xresources"
