---
- name: Sync oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.oh-my-zsh"

- name: Sync spacemacs
  git: repo=https://github.com/syl20bnr/spacemacs.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.emacs.d"

- stat: path=/vagrant
  register: vagrant_dir

- name: Clone dotfiles repo over SSH
  git: repo=git@github.com:alanctkc/dotfiles.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.config/dotfiles"
  when: not vagrant_dir.stat.exists
  register: ssh_clone
  ignore_errors: True

- name: Clone dotfiles repo over HTTPS
  git: repo=https://github.com/alanctkc/dotfiles.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.config/dotfiles"
  when: ssh_clone|failed and not vagrant_dir.stat.exists
  ignore_errors: True

- name: Symlink dotfiles repo
  file: src=/vagrant
        dest="{{ansible_env.HOME}}/.config/dotfiles"
        state=link
  when: vagrant_dir.stat.isdir is defined and vagrant_dir.stat.isdir

- name: Link all dotfiles
  command: ./dotme.sh
  args:
    chdir: "{{ansible_env.HOME}}/.config/dotfiles"
    creates: "{{ansible_env.HOME}}/.dotted"
