---
- name: Install Vagrant and Virtualbox
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - vagrant
    - virtualbox
    - linux49-virtualbox-host-modules

- name: Enable the vboxdrv module
  become: yes
  modprobe:
    name: vboxdrv
    state: present

# Vagrant doesn't expect an Arch install to have /etc/manjaro-release
# See:
# - https://classicforum.manjaro.org/index.php?topic=31002.0
# - https://github.com/mitchellh/vagrant/blob/a6c7cc48/plugins/hosts/arch/host.rb#L7
- name: Make Vagrant recognize Arch platform
  become: yes
  file:
    src: /etc/manjaro-release
    dest: /etc/arch-release
    state: link

- name: Create vagrant group
  become: yes
  group:
    name: vagrant
    state: present

- name: Add current user to the vagrant group
  become: yes
  user:
    name: "{{ansible_env.USER}}"
    groups: vagrant
    append: yes

- name: Provide vagrant group sudo access for NFS
  become: yes
  copy:
    src: vagrant-syncedfolders
    dest: /etc/sudoers.d/vagrant-syncedfolders
