---
- name: Install Vagrant and Virtualbox
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - vagrant
    - virtualbox
    - linux49-virtualbox-host-modules

- name: Enable the vboxdrv module
  become: yes
  modprobe:
    name: vboxdrv
    state: present
