#!/usr/bin/env bash

export BW_SESSION=$(cat ~/.bwsess)

list=$(bw list items | jq -c '.[] | select(.type | contains(1))')
names=$(echo "$list" | jq -r '.name')
passwords=$(echo "$list" | jq -r '.login.password')
selection=$(echo "$list" | jq -r '"\(.name):\(.login.username)"' | rofi -dmenu -matching fuzzy -i -p "pass" -format i -kb-custom-1 "Ctrl+c")
result="$?"

name=$(echo "$names" | sed -n "$((selection+1))p")
pass=$(echo "$passwords" | sed -n "$((selection+1))p")

auto_clear_clipboard() {
    sleep 30
    echo -n "" | xclip -sel clipboard
}

if [ "$result" = "0" ]; then
    echo -n $pass | xdotool type --clearmodifiers --file -
elif [ "$result" = "10" ]; then
    echo -n $pass | xclip -sel clipboard
    zenity --notification --window-icon emblem-warning --text "$name password copied to clipboard for 30 seconds"
    auto_clear_clipboard &
    disown
fi
