#!/usr/bin/env bash

pass=$(gopass list --flat | rofi -dmenu -matching fuzzy -i -p "pass" -kb-custom-1 "Ctrl+c")
if [ "$?" = "10" ]; then
    gopass show -c $pass
else
    gopass show -o $pass | xdotool type --clearmodifiers --file -
fi
