#!/usr/bin/env bash

pass=$(gopass list --flat | rofi -dmenu -matching fuzzy -i -p "pass" -kb-custom-1 "Ctrl+c")
result="$?"
if [ "$result" = "10" ]; then
    gopass show -c $pass
elif [ ! -z "$pass" ]; then
    gopass show -o $pass | xdotool type --clearmodifiers --file -
fi
