---
- name: Remove non-Infinality versions of dependencies
  become: yes
  pacman: name={{item}}
          state=absent
          force=yes
  with_items:
    - freetype2
    - fontconfig
    - cairo

- name: Install Infinality patches and Mac fonts
  yaourt: name={{item}}
          state=present
  with_items:
    - freetype2-infinality
    - fontconfig-infinality
    - cairo-infinality
    - ttf-mac-fonts

- name: Install Ubuntu font family
  become: yes
  pacman: name=ttf-ubuntu-font-family
          state=present

- name: Disable hinting in Xft settings
  become: yes
  lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
  args:
    regexp: "^Xft.hinting:"
    line: "Xft.hinting: 0"

- name: Disable hinting in font config
  become: yes
  file: src=/etc/fonts/conf.avail/10-unhinted.conf
        dest=/etc/fonts/conf.d/10-unhinted.conf
        state=link

- name: Enable autohint in Xft settings
  become: yes
  lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
  args:
    regexp: "^Xft.autohint:"
    line: "Xft.autohint: 1"

- name: Enable autohint in font config
  become: yes
  file: src=/etc/fonts/conf.avail/10-autohint.conf
        dest=/etc/fonts/conf.d/10-autohint.conf
        state=link

- name: Set slight hintstyle in Xft settings
  become: yes
  lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
  args:
    regexp: "^Xft.hintstyle:"
    line: "Xft.hintstyle: hintslight"

- name: Set slight hintstyle in font config
  become: yes
  file: src=/etc/fonts/conf.avail/10-hinting-slight.conf
        dest=/etc/fonts/conf.d/10-hinting-slight.conf
        state=link

- name: Set default LCD filter in Xft settings
  become: yes
  lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
  args:
    regexp: "^Xft.lcdfilter:"
    line: "Xft.lcdfilter: lcddefault"

- name: Set default LCD filter in font config
  become: yes
  file: src=/etc/fonts/conf.avail/11-lcdfilter-default.conf
        dest=/etc/fonts/conf.d/11-lcdfilter-default.conf
        state=link

# - name: Set OS X style in Infinality
#   become: yes
#   file: src=/etc/fonts/infinality/styles.conf.avail/osx
#         dest=/etc/fonts/infinality/conf.d
#         state=link

# - name: Set OS X style in settings script
#   become: yes
#   lineinfile: dest=/etc/profile.d/infinality-settings.sh
#               regexp="^USE_STYLE="
#               line="USE_STYLE=\"OSX\""
#               create=yes
