---
- name: Install font custom facts
  become: yes
  copy: src=fonts.fact
        dest=/etc/ansible/facts.d/fonts.fact
        mode=0755

- name: Reload ansible local facts
  setup: filter=ansible_local

- name: Configure Infinality bundle repositories
  become: yes
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [{{item.repo}}]
      Server = {{item.server}}
    marker: "# {mark} INFINALITY CONFIG FOR {{item.mark}}"
  with_items:
    - { mark: "BASE", repo: "infinality-bundle", server: "http://bohoomil.com/repo/$arch" }
    - { mark: "MULTILIB", repo: "infinality-bundle-multilib", server: "http://bohoomil.com/repo/multilib/$arch" }
    - { mark: "FONTS", repo: "infinality-bundle-fonts", server: "http://bohoomil.com/repo/fonts" }

- name: Import and sign Infinality server key
  become: yes
  command: "{{item}}"
  with_items:
    - pacman-key -r 962DDE58 
    - pacman-key --lsign-key 962DDE58
  when: not ansible_local.fonts.bohoomil_key_signed

- name: Remove non-Infinality versions of dependencies
  become: yes
  pacman: name={{item}}
          state=absent
          update_cache=yes
          force=yes
  with_items:
    - freetype2
    - fontconfig
    - cairo
    - ttf-dejavu
    - ttf-liberation
    - noto-fonts
    - tex-gyre-fonts
    - gsfonts
    - ttf-droid
    - ttf-ubuntu-font-family

- name: Install Infinality multilib bundle with fonts
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - infinality-bundle-multilib
    - ibfonts-meta-extended

- name: Install font manager and MS/Mac fonts
  yaourt: name={{item}}
          state=present
  with_items:
    - font-manager
    - ttf-ms-fonts
    - ttf-mac-fonts

# - name: Disable hinting in Xft settings
#   become: yes
#   lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
#   args:
#     regexp: "^Xft.hinting:"
#     line: "Xft.hinting: 0"

# - name: Disable hinting in font config
#   become: yes
#   file: src=/etc/fonts/conf.avail/10-unhinted.conf
#         dest=/etc/fonts/conf.d/10-unhinted.conf
#         state=link

# - name: Enable autohint in Xft settings
#   become: yes
#   lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
#   args:
#     regexp: "^Xft.autohint:"
#     line: "Xft.autohint: 1"

# - name: Enable autohint in font config
#   become: yes
#   file: src=/etc/fonts/conf.avail/10-autohint.conf
#         dest=/etc/fonts/conf.d/10-autohint.conf
#         state=link

# - name: Set slight hintstyle in Xft settings
#   become: yes
#   lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
#   args:
#     regexp: "^Xft.hintstyle:"
#     line: "Xft.hintstyle: hintslight"

# - name: Set slight hintstyle in font config
#   become: yes
#   file: src=/etc/fonts/conf.avail/10-hinting-slight.conf
#         dest=/etc/fonts/conf.d/10-hinting-slight.conf
#         state=link

# - name: Set default LCD filter in Xft settings
#   become: yes
#   lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
#   args:
#     regexp: "^Xft.lcdfilter:"
#     line: "Xft.lcdfilter: lcddefault"

# - name: Set default LCD filter in font config
#   become: yes
#   file: src=/etc/fonts/conf.avail/11-lcdfilter-default.conf
#         dest=/etc/fonts/conf.d/11-lcdfilter-default.conf
#         state=link

# - name: Copy Infinality generic config
#   become: yes
#   copy: src=/usr/share/doc/freetype2-infinality-ultimate/infinality-settings-generic
#         dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh

# - name: Set OS X style in config
#   become: yes
#   lineinfile: dest=/etc/X11/xinit/xinitrc.d/xft-settings.sh
#               regexp="^USE_STYLE="
#               line="USE_STYLE=\"OSX\""
#               create=yes
