---
- name: Install font custom facts
  become: yes
  copy: src=fonts.fact
        dest=/etc/ansible/facts.d/fonts.fact
        mode=0755

- name: Reload ansible local facts
  setup: filter=ansible_local

- name: Configure Infinality bundle repositories
  become: yes
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [{{item.repo}}]
      Server = {{item.server}}
    marker: "# {mark} INFINALITY CONFIG FOR {{item.mark}}"
  with_items:
    - { mark: "BASE", repo: "infinality-bundle", server: "http://bohoomil.com/repo/$arch" }
    - { mark: "MULTILIB", repo: "infinality-bundle-multilib", server: "http://bohoomil.com/repo/multilib/$arch" }
    - { mark: "FONTS", repo: "infinality-bundle-fonts", server: "http://bohoomil.com/repo/fonts" }

- name: Import and sign Infinality server key
  become: yes
  command: "{{item}}"
  with_items:
    - pacman-key -r 962DDE58 
    - pacman-key --lsign-key 962DDE58
  when: not ansible_local.fonts.bohoomil_key_signed

- name: Remove non-Infinality versions of dependencies
  become: yes
  pacman: name={{item}}
          state=absent
          force=yes
  with_items:
    - freetype2
    - fontconfig
    - cairo
    - ttf-dejavu
    - ttf-liberation
    - noto-fonts
    - tex-gyre-fonts
    - gsfonts
    - ttf-droid
    - ttf-ubuntu-font-family

- name: Install Infinality multilib bundle with fonts
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - infinality-bundle-multilib
    - ibfonts-meta-extended

- name: Install font manager and additional fonts
  yaourt: name={{item}}
          state=present
  with_items:
    - font-manager
    - ttf-ms-fonts
    - ttf-mac-fonts
    - ttf-unifont

- name: Copy Infinality settings
  become: yes
  command: cp /usr/share/doc/freetype2-infinality-ultimate/infinality-settings.sh /etc/profile.d/infinality-settings.sh
  args:
    creates: /etc/profile.d/infinality-settings.sh

- name: Set OS X style in Infinality config
  become: yes
  lineinfile: dest=/etc/profile.d/infinality-settings.sh
              regexp="^export INFINALITY_FT="
              line="export INFINALITY_FT=\"osx\""

- name: Remove user font config and default Infinality repl config
  become: yes
  file: path={{item}}
        state=absent
  with_items:
    - "{{ansible_env.HOME}}/.config/fontconfig/fonts.conf"
    - /etc/fonts/conf.d/37-repl-global-free.conf

- name: Configure Liberation aliases 
  become: yes
  copy: src=35-repl-custom.conf
        dest=/etc/fonts/conf.d/35-repl-custom.conf
