---
- name: Install font manager and additional fonts
  yaourt: name={{item}}
          state=present
  with_items:
    - font-manager
    - ttf-ubuntu-font-family
    - ttf-ms-fonts
    - ttf-mac-fonts
    - ttf-unifont
