---
- name: Install core packages
  become: yes
  dnf:
    name:
      - ansible
      - diceware
      - byobu
      - flameshot
      - ripgrep
      - jq
      - lsd
      - bat
      - ImageMagick
      - xclip
      - pandoc
      - paperkey
      - ncdu
      - xprop # used by pixel saver in gnome
      - yubikey-manager
      - cargo
    update_cache: yes

- name: Ensure local bin path exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Install rbw
  shell: cargo install rbw
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rbw"
