---
- name: Install core packages
  become: yes
  apt:
    name:
      - build-essential
      - software-properties-common
      - python-is-python3
      - regolith-look-dracula # TODO move to i3 role
      - ansible
      - curl
      - git
      - vim
      - byobu
      - ranger
      - ripgrep
      - jq
      - cmake
      - imagemagick
      - whois
      - ldnsutils
      - markdown
      - acpi
      - i3xrocks-battery # TODO move to i3 role
      - fonts-noto-core # TODO move to emacs role
      - fonts-source-code-pro-ttf
      - fonts-hack-ttf # TODO move to emacs role
      - unifont # TODO move to emacs role
    update_cache: yes
