---
- name: Install core packages
  become: yes
  apt:
    name:
      - build-essential
      - software-properties-common
      - gnome-disk-utility
      - checkinstall
      - dconf-editor
      - ansible
      - curl
      - git
      - gnupg
      - rng-tools
      - byobu
      - flameshot
      - ripgrep
      - seahorse
      - jq
      - cmake
      - imagemagick
      - xclip
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - pandoc
      - paperkey
      - whois
      - ldnsutils
      - markdown
      - ncdu
      - acpi
      - unzip
      - tree
    update_cache: yes

- name: Ensure local bin path exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Install lsd
  become: yes
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.19.0/lsd_0.19.0_amd64.deb

- name: Install lf
  become: yes
  apt:
    deb: https://download.opensuse.org/repositories/home:/Provessor/xUbuntu_20.04/amd64/lf_16+git20200907.61442f8-1_amd64.deb

- name: Install cadmus
  become: yes
  apt:
    deb: https://github.com/josh-richardson/cadmus/releases/download/0.0.3/cadmus.deb

- name: Install bitwarden
  become: yes
  apt:
    deb: https://github.com/bitwarden/desktop/releases/download/v1.25.1/Bitwarden-1.25.1-amd64.deb

- name: Install bitwarden CLI
  unarchive:
    src: https://github.com/bitwarden/cli/releases/download/v1.15.1/bw-linux-1.15.1.zip
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: +x
    remote_src: yes
