---
- name: Install core packages
  become: yes
  dnf:
    name:
      - ansible
      - diceware
      - byobu
      - flameshot
      - ripgrep
      - jq
      - lsd
      - bat
      - ImageMagick
      - xclip
      - pandoc
      - paperkey
      - htop
      - ncdu
      - xprop # used by pixel saver in gnome
      - yubikey-manager
      - cargo
      - gcc-c++
      - rubygem-gist
      - dconf-editor
      - gnome-extensions-app
      - gnome-tweaks
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - libpq-devel
      - postgresql
      - fd-find

    update_cache: yes

- name: Install rbw
  shell: cargo install rbw
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rbw"

- name: Copy rbw to bin on PATH
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: +x
  with_items:
    - src: "{{ ansible_env.HOME }}/.cargo/bin/rbw"
      dest: /usr/local/bin/rbw
    - src: "{{ ansible_env.HOME }}/.cargo/bin/rbw-agent"
      dest: /usr/local/bin/rbw-agent

- name: Configure flathub
  become: yes
  community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
