---
- name: Install core packages
  become: yes
  dnf:
    name:
      - ansible
      - diceware
      - flameshot
      - ripgrep
      - jq
      - lsd
      - bat
      - ImageMagick
      - xclip
      - pandoc
      - paperkey
      - htop
      - ncdu
      - xprop # used by pixel saver in gnome
      - yubikey-manager
      - cargo
      - gcc-c++
      - rubygem-gist
      - dconf-editor
      - gnome-extensions-app
      - gnome-tweaks
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - libpq-devel
      - postgresql
      - fd-find
      - oniguruma-devel
      - libacl-devel
      - libcap-devel
      - libjpeg-turbo-devel
      - libjpeg-turbo-utils
      - python3-devel
      - libxslt-devel
      - dbus-devel

    update_cache: yes

- name: Install rbw and dust
  shell: "cargo install {{ item.crate }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.bin }}"
  with_items:
    - crate: rbw
      bin: rbw
    - crate: du-dust
      bin: dust

- name: Copy rbw and dust to bin on PATH
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/.cargo/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: +x
  with_items:
    - rbw
    - rbw-agent
    - dust

- name: Configure flathub
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
