---
- name: Install core packages
  become: yes
  apt:
    name:
      - build-essential
      - software-properties-common
      - python-is-python3
      - ansible
      - curl
      - git
      - ranger
      - ripgrep
      - jq
      - cmake
      - whois
      - ldnsutils
      - markdown
    update_cache: yes
