---
- name: Install core packages
  become: yes
  apt:
    name:
      - build-essential
      - software-properties-common
      - checkinstall
      - ansible
      - curl
      - git
      - vim
      - byobu
      - ranger
      - ripgrep
      - jq
      - cmake
      - imagemagick
      - whois
      - ldnsutils
      - markdown
      - acpi
      - unzip
      - tree
      - units
    update_cache: yes

- name: Insure local bin path exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
