---
- name: Install core packages
  become: yes
  dnf:
    name:
      - ansible
      - diceware
      - byobu
      - flameshot
      - peek
      - ripgrep
      - seahorse
      - jq
      - lsd
      - ImageMagick
      - xclip
      - pandoc
      - paperkey
      - ncdu
    update_cache: yes

- name: Ensure local bin path exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Install lf
  become: yes
  unarchive:
    src: https://github.com/gokcehan/lf/releases/download/r26/lf-linux-amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: +x
    remote_src: yes

# TODO use cargo
# - name: Install rbw
#   become: yes
#   apt:
#     deb: https://git.tozt.net/rbw/releases/deb/rbw_1.2.0_amd64.deb
