---
- name: Add RPM Fusion GPG keys
  become: yes
  rpm_key:
    key: "{{ item }}"
  with_items:
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Enable the RPM Fusion repositories
  become: yes
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install core packages
  become: yes
  dnf:
    name:
      - dnf-plugins-core
      - ansible
      - diceware
      - flameshot
      - ripgrep
      - jq
      - lsd
      - bat
      - age
      - fastfetch
      - powertop
      - ImageMagick
      - xclip
      - pandoc
      - paperkey
      - htop
      - ncdu
      - xprop # used by pixel saver in gnome
      - yubikey-manager
      - cargo
      - gcc-c++
      - rubygem-gist
      - dconf-editor
      - gnome-extensions-app
      - gnome-tweaks
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - libpq-devel
      - postgresql
      - fd-find
      - oniguruma-devel
      - libacl-devel
      - libcap-devel
      - libjpeg-turbo-devel
      - libjpeg-turbo-utils
      - python3-devel
      - libxslt-devel
      - dbus-devel
      - libxcrypt-compat
      - patch
    update_cache: yes

- name: Install ffmpeg from RPM Fusion
  become: yes
  dnf:
    allowerasing: true
    name: ffmpeg

- name: Remove flathub remote
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: absent

- name: Re-configure flathub
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install step cli
  become: yes
  dnf:
    name: https://dl.step.sm/gh-release/cli/gh-release-header/v0.19.0/step-cli_0.19.0_amd64.rpm
    disable_gpg_check: yes

- name: Install rbw and dust
  shell: "cargo install {{ item.crate }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.bin }}"
  with_items:
    - crate: rbw
      bin: rbw
    - crate: du-dust
      bin: dust
