---
- name: Install synaptics Xorg config
  become: yes
  copy: src=/usr/share/X11/xorg.conf.d/40-libinput.conf
        dest=/etc/X11/xorg.conf.d/40-libinput.conf
        force=no
        
- name: Configure scroll edge
  become: yes
  lineinfile: dest=/etc/X11/xorg.conf.d/40-libinput.conf
              line="        Option \"VertEdgeScroll\" \"off\""
              state=present
              insertafter="Identifier \"libinput touchpad catchall\""
