---
- name: Install nvm
  include_role:
    name: moviedo.nvm
  vars:
    nvm_user: "{{ ansible_env.USER }}"
    nvm_version: v0.37.2
    nvm_node_version: v14.15.5

- name: Install common node tools
  community.general.npm:
    name: "{{ item }}"
    global: yes
    executable: "{{ ansible_env.HOME }}/.nvm/versions/node/v14.15.5/bin/npm"
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v14.15.5/bin:{{ ansible_env.PATH }}"
  with_items:
    - yarn
    - typescript
    - eslint
    - babel-eslint
    - eslint-plugin-react
    - prettier
    - js-beautify
    - import-js
    - vmd
