---
- name: Install fnm
  unarchive:
    src: https://github.com/Schniz/fnm/releases/download/v1.22.9/fnm-linux.zip
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: +x
    remote_src: yes

- name: Install nodejs
  shell: fnm install v14.15.5
  args:
    creates: "{{ ansible_env.HOME }}/.fnm/node-versions/v14.15.5"

- name: Install common node tools
  community.general.npm:
    name: "{{ item }}"
    global: yes
    executable: "{{ ansible_env.HOME }}/.fnm/node-versions/v14.15.5/installation/bin/npm"
  with_items:
    - yarn
    - typescript
    - eslint
    - babel-eslint
    - eslint-plugin-react
    - prettier
    - js-beautify
    - import-js
    - vmd
