---
- name: Install common packages
  pip:
    name:
      - pip
      - pipenv
      - poetry
      - requests
      - prompt-toolkit
      - yaspin
      - python-lsp-server[all]
      - ruff
      - ruff-lsp
      - pyright
      - importmagic
      - epc
      - pytest

- name: Install pyenv
  shell: "curl https://pyenv.run | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
