---
- name: Install base tools
  become: yes
  dnf:
    name:
      - pipenv
      - python3-ipython

- name: Install common packages
  pip:
    name:
      - requests
      - prompt-toolkit
      - yaspin
      - python3-pip-autoremove
      # used in spacemacs
      - importmagic
      - epc
