---
- name: Install base tools
  become: yes
  apt:
    name:
      - python-is-python3
      - python3-pip
      - ipython3

- name: Install common packages
  pip:
    name:
      - requests
      - prompt-toolkit
      - yaspin
      - python3-pip-autoremove
      # used in spacemacs
      - importmagic
      - epc
    executable: pip3
