---
- name: Install base tools
  become: yes
  dnf:
    name:
      - pipenv
      - python3-ipython

- name: Install common packages
  pip:
    name:
      - requests
      - prompt-toolkit
      - yaspin
      - python3-pip-autoremove
      - python-lsp-server[all]
      - black
      - importmagic
      - epc
      - flake8
      - autoflake
      - ptvsd>=4.2

- name: Install pyenv
  shell: "curl https://pyenv.run | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"

- name: Symlink pyenv
  file:
    src: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
    dest: "{{ ansible_env.HOME }}/.local/bin/pyenv"
    state: link
