---
- name: Install base tools
  become: yes
  dnf:
    name:
      - python3-ipython

- name: Install common packages
  pip:
    name:
      - pip
      - pipenv
      - poetry
      - requests
      - prompt-toolkit
      - yaspin
      - python-lsp-server[all]
      - black
      - importmagic
      - epc
      - flake8
      - autoflake
      - ptvsd>=4.2

- name: Install pyenv
  shell: "curl https://pyenv.run | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
