#!/usr/bin/env bash
set -e
password=$(secret-tool lookup ykman oath)
credential=$(ykman oath --password $password code | rofi -dmenu -i -p "yubikey:" $@)
if [[ ! -z "${credential// }" ]]
then
    service=$(echo $credential | cut -d: -f 1)
    token=$(echo $credential | awk '{print $NF}')
    printf $token | xclip -selection clipboard
    notify-desktop "YubiKey" "$service token copied to clipboard."
fi
