#!/usr/bin/env bash
set -e
path=$(find $HOME -type d | rofi -dmenu -i -p "project:" $@)
session=$(echo $(basename $path) | sed -r 's/\./_/g')
termite -d $path -e "sh -c 'tmux new-session -s $session || tmux attach-session -t $session'"
