#!/usr/bin/env bash
set -e
shorthand=$(printf '%s\n' ~/Projects/* | cut -d '/' -f 5,7 | rofi -dmenu -matching fuzzy -i -p "project" $@)
parts=(${shorthand//\// })
path=~/Projects/${parts[0]}
session=$(echo $(basename $path) | sed -r 's/\./_/g')
kitty --single-instance sh -c "byobu new-session -c $path -s $session 2> /dev/null || byobu attach-session -t $session"
