#!/usr/bin/env bash

if [ "$1" == "up" ]
then
    amixer -D pulse sset Master 5%+
elif [ "$1" == "down" ]
then
  amixer -D pulse sset Master 5%-
elif [ "$1" == "mute" ]
then
    amixer -D pulse set Master 1+ toggle
else
    echo "Options are 'up', 'down', or 'mute' (to toggle)."
    exit 1
fi

pkill -SIGRTMIN+5 i3blocks
if [ "$1" != "down" ]
then
    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
fi
