---
- name: Install vim
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - vim

- name: Configure basic vimrc
  get_url: url=https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
           dest="{{ansible_env.HOME}}/.vimrc"

- name: Configure color scheme
  lineinfile: dest="{{ansible_env.HOME}}/.vimrc"
              line={{item}}
  with_items:
    - set t_ut=
    - set background=dark
    - colorscheme elflord
