#!/usr/bin/env bash

kill_session=false
shorthand=$(printf '%s\n' ~/Projects/* | cut -d '/' -f 5,7 | rofi -dmenu -matching fuzzy -sorting-method fzf -i -p "project" -kb-custom-1 "Ctrl+x" $@)
result="$?"
if [ "$result" = "1" ]; then
    exit;
elif [ "$result" = "10" ]; then
    kill_session=true;
fi
parts=(${shorthand//\// })
path=~/Projects/${parts[0]}
session=$(echo $(basename $path) | sed -r 's/\./_/g')
if [ "$kill_session" = "true" ]; then
    tmux kill-session -t $session
    notify-send "Session killed" "Killed session $session"
    exit;
fi
tmux list-sessions -F '#{session_name}' | grep "^$session\$" > /dev/null && (alacritty --title $session --command tmux attach-session -t $session & notify-send "Existing session" "Opening existing session $session" && exit)
alacritty --title $session --command tmux new-session -c $path -s $session &
