#!/usr/bin/env bash

export PATH="$PATH:$HOME/.cargo/bin"

list=$(rbw list --fields id,name,user | awk -F'\t' 'length($3)')
ids=$(echo "$list" | cut -f1)
names=$(echo "$list"  | cut -f2)
selection=$(echo "$list" | cut -f2,3 --output-delimiter=: | rofi -dmenu -matching fuzzy -sorting-method fzf -i -p "pass" -format i -kb-custom-1 "Ctrl+c")
result="$?"

id=$(echo "$ids" | sed -n "$((selection+1))p")
name=$(echo "$names" | sed -n "$((selection+1))p")
pass=$(rbw get $id)

auto_clear_clipboard() {
    sleep 30
    echo -n "" | xclip -sel clipboard
}

if [ "$result" = "0" ]; then
    echo -n $pass | xdotool type --clearmodifiers --file -
elif [ "$result" = "10" ]; then
    echo -n $pass | xclip -sel clipboard
    notify-send "Password copied" "$name password copied to clipboard for 30 seconds"
    auto_clear_clipboard &
    disown
fi
