---
- name: Install python base
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - python-pip

- name: Install python tooling
  become: yes
  pip: name={{item}}
       state=present
  with_items:
    - virtualenvwrapper
    - flake8
    - ipython
    - autoflake
    - yapf
