---
- name: Install git and related tools
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - git
    - gist

- name: Install git LFS
  yaourt:
    name: git-lfs-bin
    state: present

- name: Install deepgit
  yaourt:
    name: deepgit
    state: present
