---
- name: Authorize sudo for Karabiner pkg install
  ansible.builtin.shell: "echo '{{ ansible_become_password }}' | sudo -S true"
  no_log: true
  changed_when: false

- name: Install Karabiner-Elements
  community.general.homebrew_cask:
    name: karabiner-elements

- name: Create Karabiner config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/karabiner"
    state: directory

- name: Deploy Karabiner configuration
  ansible.builtin.copy:
    src: files/karabiner.json
    dest: "{{ ansible_env.HOME }}/.config/karabiner/karabiner.json"
