---
- name: Disable extension version validation
  community.general.dconf:
    key: "/org/gnome/shell/disable-extension-version-validation"
    value: "true"

- name: Create backgrounds and themes directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/.local/share/backgrounds"
    - "{{ ansible_env.HOME }}/.themes"

- name: Copy wallpaper graphic
  copy:
    src: files/dracula-arab-tile.png
    dest: "{{ ansible_env.HOME }}/.local/share/backgrounds/dracula-arab-tile.png"

- name: Set wallpaper
  community.general.dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ ansible_env.HOME }}/.local/share/backgrounds/dracula-arab-tile.png'"

- name: Download Dracula GTK theme
  unarchive:
    src: https://github.com/dracula/gtk/releases/download/v3.0/Dracula.tar.xz
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/.themes"

- name: Set GTK theme
  community.general.dconf:
    key: "{{ item }}"
    value: "'Dracula'"
  with_items:
    - /org/gnome/desktop/interface/gtk-theme
    - /org/gnome/desktop/wm/preferences/theme

- name: Install papirus icon theme
  become: yes
  dnf:
    name: papirus-icon-theme
  register: papirus_icons

- name: Set icon theme
  community.general.dconf:
    key: /org/gnome/desktop/interface/icon-theme
    value: "'Papirus'"

- name: Set 12h clock format
  community.general.dconf:
    key: /org/gnome/desktop/interface/clock-format
    value: "'12h'"

- name: Turn off dynamic workspaces
  community.general.dconf:
    key: /org/gnome/mutter/dynamic-workspaces
    value: "false"

- name: Use 4 workspaces
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/num-workspaces
    value: "4"

- name: Show only current workspace windows in app switcher
  community.general.dconf:
    key: /org/gnome/shell/app-switcher
    value: "true"

- name: Define desktop keybindings
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: close
      value: "['<Shift><Super>q']"
    - key: minimize
      value: "['<Super>Escape']"
    - key: maximize
      value: "['<Shift><Super>k']"
    - key: unmaximize
      value: "['<Shift><Super>j']"
    - key: switch-applications
      value: "['<Super>l']"
    - key: switch-applications-backward
      value: "['<Super>h']"
    - key: switch-group
      value: "['<Super>j']"
    - key: switch-group-backward
      value: "['<Super>k']"
    - key: switch-to-workspace-left
      value: "['<Super>comma']"
    - key: switch-to-workspace-right
      value: "['<Super>period']"
    - key: move-to-workspace-left
      value: "['<Shift><Super>less']"
    - key: move-to-workspace-right
      value: "['<Shift><Super>greater']"
    - key: switch-to-workspace-1
      value: "['<Super>1']"
    - key: switch-to-workspace-2
      value: "['<Super>2']"
    - key: switch-to-workspace-3
      value: "['<Super>3']"
    - key: switch-to-workspace-4
      value: "['<Super>4']"
    - key: move-to-workspace-1
      value: "['<Shift><Super>exclam']"
    - key: move-to-workspace-2
      value: "['<Shift><Super>at']"
    - key: move-to-workspace-3
      value: "['<Shift><Super>numbersign']"
    - key: move-to-workspace-4
      value: "['<Shift><Super>dollar']"
    - key: move-to-monitor-down
      value: "['<Primary><Super>j']"
    - key: move-to-monitor-left
      value: "['<Primary><Super>h']"
    - key: move-to-monitor-right
      value: "['<Primary><Super>l']"
    - key: move-to-monitor-up
      value: "['<Primary><Super>k']"

- name: Define lock screen keybinding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver"
    value: "['<Shift><Super>Escape']"

- name: Remove default screenshot keybinding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screenshot"
    value: "@as []"

- name: Define ulauncher keybinding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: name
      value: "'Ulauncher'"
    - key: binding
      value: "'<Super>space'"
    - key: command
      value: "'ulauncher-toggle'"

- name: Define full screen terminal keybinding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: name
      value: "'Tilix'"
    - key: binding
      value: "'<Super>Return'"
    - key: command
      value: "'tilix --maximize'"

- name: Define flameshot keybinding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: name
      value: "'Flameshot'"
    - key: binding
      value: "'<Super>Print'"
    - key: command
      value: "'flameshot gui'"

- name: Show custom keybindings in settings
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/']"

- name: Configure system monitor
  community.general.dconf:
    key: "/org/gnome/shell/extensions/system-monitor/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: center-display
      value: "false"
    - key: compact-display
      value: "false"
    - key: cpu-nice-color
      value: "'#8be9fdff'"
    - key: cpu-show-text
      value: "true"
    - key: cpu-style
      value: "'both'"
    - key: cpu-system-color
      value: "'#bc93f9ff'"
    - key: cpu-user-color
      value: "'#44475aff'"
    - key: disk-display
      value: "false"
    - key: icon-display
      value: "false"
    - key: memory-display
      value: "false"
    - key: move-clock
      value: "false"
    - key: net-display
      value: "false"
    - key: show-tooltip
      value: "false"
