---
- name: Install psutil
  become: yes
  apt:
    name: python3-psutil

- name: Create backgrounds directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/backgrounds"
    state: directory

- name: Copy wallpaper graphic
  copy:
    src: files/dracula-arab-tile.png
    dest: "{{ ansible_env.HOME }}/.local/share/backgrounds/dracula-arab-tile.png"

- name: Set wallpaper
  community.general.dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ ansible_env.HOME }}/.local/share/backgrounds/dracula-arab-tile.png'"

- name: Add papirus PPA
  become: yes
  apt_repository:
    repo: ppa:papirus/papirus

- name: Install papirus icon theme
  become: yes
  apt:
    name: papirus-icon-theme
    update_cache: yes
  register: papirus_icons

- name: Set icon theme
  community.general.dconf:
    key: /org/gnome/desktop/interface/icon-theme
    value: "'Papirus'"

- name: Set 12h clock format
  community.general.dconf:
    key: /org/gnome/desktop/interface/clock-format
    value: "'12h'"
