---
- name: Add Moka icon theme PPA
  become: yes
  apt_repository: repo="ppa:moka/daily"

- name: Install Moka icon theme
  become: yes
  apt: name=moka-icon-theme
       state=installed

- name: Clone Arc icon theme
  become: yes
  git: repo=https://github.com/horst3180/arc-icon-theme
       depth=1
       accept_hostkey=true
       dest=/usr/local/src/arc-icon-theme

- name: Install Arc icon theme
  become: yes
  synchronize: src=/usr/local/src/arc-icon-theme/Arc
        dest=/usr/share/icons

- name: Set icon theme to Arc
  command: gsettings set org.gnome.desktop.interface icon-theme "Arc"
