---
- name: Install icon custom facts
  become: yes
  copy: src=icons.fact
        dest=/etc/ansible/facts.d/icons.fact
        mode=0755

- name: Reload ansible local facts
  setup: filter=ansible_local

- name: Install Arc icon theme
  become: yes
  pacman: name=arc-icon-theme
          state=present

- name: Set icon theme to Arc for GTK+ 2
  lineinfile: dest="{{ansible_env.HOME}}/.gtkrc-2.0"
              regexp="^gtk-icon-theme-name="
              line="gtk-icon-theme-name=\"Arc\""
              create=yes

- name: Set icon theme to Arc for GTK+ 3
  lineinfile: dest="{{ansible_env.HOME}}/.config/gtk-3.0/settings.ini"
              regexp="^gtk-icon-theme-name="
              line="gtk-icon-theme-name=Arc"
              create=yes

- name: Set icon theme to Arc in Gnome settings
  command: gsettings set org.gnome.desktop.interface icon-theme "Arc"
  when: ansible_local.icons.icon_theme != "Arc"
