---
- name: Install Arc icon theme
  become: yes
  pacman: name=arc-icon-theme
          state=present

- name: Set icon theme to Arc
  lineinfile: dest="{{ansible_env.HOME}}/.gtkrc-2.0"
              regexp="^gtk-icon-theme-name="
              line="gtk-icon-theme-name=\"Arc\""
              create=yes
