---
- name: Add kubernetes repo
  become: yes
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repo
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
    gpgkey:
      - https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
    exclude:
      - kubelet
      - kubeadm
      - kubectl
      - cri-tools
      - kubernetes-cni

- name: Install kubectl and helm
  become: yes
  dnf:
    name:
      - kubectl

- name: Make sure local bin dir exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Download kustomize
  unarchive:
    src: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.5.0/kustomize_v5.5.0_linux_amd64.tar.gz
    dest: "{{ ansible_env.HOME}}/.local/bin"
    remote_src: yes
    mode: +x
    extra_opts:
      - kustomize

- name: Install k9s
  become: yes
  dnf:
    name: https://github.com/derailed/k9s/releases/download/v0.32.7/k9s_linux_amd64.rpm
    disable_gpg_check: yes

- name: Make sure k9s config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/k9s"
    state: directory

- name: Configure k9s dracula theme
  get_url:
    url: https://raw.githubusercontent.com/derailed/k9s/refs/heads/master/skins/dracula.yaml
    dest: "{{ ansible_env.HOME }}/.config/k9s/skin.yml"
