---
- name: Add kubernetes GPG keys
  become: yes
  rpm_key:
    key: "{{ item }}"
  with_items:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Add kubernetes repo
  become: yes
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

- name: Install kubectl
  become: yes
  dnf:
    name: kubectl

- name: Make sure local bin dir exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Download k9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.25.18/k9s_Linux_x86_64.tar.gz
    dest: "{{ ansible_env.HOME}}/.local/bin"
    remote_src: yes
    mode: +x
    extra_opts:
      - k9s

- name: Make sure k9s config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/k9s"
    state: directory

- name: Configure k9s dracula theme
  get_url:
    url: https://raw.githubusercontent.com/derailed/k9s/master/skins/dracula.yml
    dest: "{{ ansible_env.HOME }}/.config/k9s/skin.yml"
