---
- name: Tap emacs-plus
  community.general.homebrew_tap:
    name: d12frosted/emacs-plus

- name: Install emacs-plus
  community.general.homebrew:
    name: emacs-plus@30

- name: Copy Emacs.app to Applications
  ansible.builtin.copy:
    src: /opt/homebrew/opt/emacs-plus@30/Emacs.app
    dest: /Applications/Emacs.app
    remote_src: yes

- name: Remove quarantine flag from Emacs
  ansible.builtin.command: xattr -d com.apple.quarantine /Applications/Emacs.app
  changed_when: false
  failed_when: false

- name: Install emacs support tools
  community.general.homebrew:
    name:
      - tree-sitter
      - direnv
      - shellcheck
      - shfmt
      - tidy-html5
