---
- name: Tap emacs-plus
  community.general.homebrew_tap:
    name: d12frosted/emacs-plus

- name: Install emacs-plus
  community.general.homebrew:
    name: emacs-plus@30

- name: Copy Emacs.app to Applications
  ansible.builtin.shell: |
    rm -rf /Applications/Emacs.app
    cp -R /opt/homebrew/opt/emacs-plus@30/Emacs.app /Applications/
    xattr -cr /Applications/Emacs.app
  args:
    creates: /Applications/Emacs.app

- name: Install emacs support tools
  community.general.homebrew:
    name:
      - tree-sitter
      - direnv
      - shellcheck
      - shfmt
      - tidy-html5
