---
- name: Tap emacs-plus
  community.general.homebrew_tap:
    name: d12frosted/emacs-plus

- name: Install emacs-plus
  community.general.homebrew:
    name: emacs-plus@30
    install_options: with-native-comp

- name: Install emacs support tools
  community.general.homebrew:
    name:
      - tree-sitter
      - direnv
      - shellcheck
      - shfmt
      - tidy-html5

- name: Create LaunchAgents directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/LaunchAgents"
    state: directory

- name: Install Emacs daemon launchd plist
  ansible.builtin.copy:
    src: files/com.gnu.emacs.daemon.plist
    dest: "{{ ansible_env.HOME }}/Library/LaunchAgents/com.gnu.emacs.daemon.plist"
  register: emacs_plist

- name: Load Emacs daemon launchd service
  ansible.builtin.command: launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/com.gnu.emacs.daemon.plist
  when: emacs_plist.changed
