---
- name: Add emacs native compilation repository
  become: yes
  community.general.copr:
    name: deathwish/emacs-pgtk-nativecomp

- name: Install emacs
  become: yes
  dnf:
    name: emacs

- name: Clone doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"

- name: Install doom emacs
  expect:
    command: "{{ ansible_env.HOME }}/.emacs.d/bin/doom install --no-env"
    timeout: null
    responses:
      (?i)fonts\?: y
    creates: "{{ ansible_env.HOME }}/.emacs.d/.local"

- name: Create autostart directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory

- name: Set up daemon autostart file
  copy:
    src: files/emacsd.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/emacsd.desktop"

- name: Create user applications directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory

- name: Create desktop file
  copy:
    src: files/emacs.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/emacs.desktop"
  register: emacs_unit_file

- name: Remove emacs client desktop file from rpm
  become: yes
  file:
    path: /usr/share/applications/emacsclient.desktop
    state: absent
