---
- name: Install emacs
  become: yes
  apt:
    name: emacs

- name: Clone spacemacs distribution
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    version: develop
