---
- name: Install emacs
  become: yes
  dnf:
    name: emacs

- name: Clone spacemacs distribution
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    version: develop

- name: Create user systemd directory
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory

- name: Set up systemd unit file
  copy:
    src: files/emacs.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/emacs.service"
  register: emacs_unit_file

- name: Reload systemd
  systemd:
    daemon_reload: yes
    scope: user
  when: emacs_unit_file.changed

- name: Enable and start emacs server
  systemd:
    name: emacs
    scope: user
    state: started
    enabled: yes
