---
- name: Add emacs native compilation repository
  become: yes
  community.general.copr:
    name: deathwish/emacs-pgtk-nativecomp

- name: Install emacs
  become: yes
  dnf:
    name: emacs

- name: Clone doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"

- name: Install doom emacs
  expect:
    command: "{{ ansible_env.HOME }}/.emacs.d/bin/doom install --no-env"
    timeout: null
    responses:
      (?i)fonts\?: y
    #creates: "{{ ansible_env.HOME }}/.emacs.d/.local"

- name: Create user systemd directory
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory

- name: Set up systemd unit file
  copy:
    src: files/emacs.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/emacs.service"
  register: emacs_unit_file

- name: Reload systemd
  systemd:
    daemon_reload: yes
    scope: user
  when: emacs_unit_file.changed

- name: Enable and start emacs server
  systemd:
    name: emacs
    scope: user
    state: started
    enabled: yes

- name: Create user applications directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory

- name: Create desktop file
  copy:
    src: files/emacs.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/emacs.desktop"
  register: emacs_unit_file
