---
- name: Install emacs and tree-sitter
  become: yes
  dnf:
    name:
      - emacs-pgtk
      - libtree-sitter
      - libtree-sitter-devel

- name: Clone doom emacs
  git:
    repo: https://github.com/doomemacs/doomemacs
    dest: "{{ ansible_env.HOME }}/.config/emacs"

- name: Install doom emacs
  expect:
    command: "{{ ansible_env.HOME }}/.config/emacs/bin/doom install --no-env"
    timeout: null
    responses:
      (?i)fonts\?: y
    creates: "{{ ansible_env.HOME }}/.config/emacs/.local"

- name: Sync doom packages
  command: "{{ ansible_env.HOME }}/.config/emacs/bin/doom sync"
  changed_when: false

- name: Create autostart directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory

- name: Set up daemon autostart file
  copy:
    src: files/emacsd.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/emacsd.desktop"

- name: Create user applications directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory

- name: Create desktop file
  copy:
    src: files/emacs.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/emacs.desktop"
  register: emacs_unit_file

- name: Remove emacs client desktop file from rpm
  become: yes
  file:
    path: /usr/share/applications/emacsclient.desktop
    state: absent

- name: Create notes directory for org files
  file:
    path: "{{ ansible_env.HOME }}/Documents/Notes"
    state: directory
