---
- name: Remove system python pyasn1
  become: yes
  pip:
    name: pyasn1
    state: absent

- name: Install desktop Yubico Authenticator
  yaourt: name=yubico-yubioath-desktop
          state=present

- name: Enable pcscd
  become: yes
  systemd: name=pcscd
           enabled=yes
           state=started
