---
- name: Install desktop Yubico Authenticator
  yaourt: name={{item}}
          state=present
  with_items:
    - qt5-quickcontrols
    - yubico-yubioath-desktop
    - yubikey-manager

- name: Enable pcscd
  become: yes
  systemd: name=pcscd
           enabled=yes
           state=started
