---
- name: Install desktop Yubico Authenticator
  yaourt: name={{item}}
          state=present
  with_items:
    - acsccid
    - yubico-yubioath-desktop

- name: Enable pcscd
  become: yes
  systemd: name=pcscd
           enabled=yes
           state=started
