---
- name: Install CUPS Cloud Print dependencies
  become: yes
  apt: name={{item}}
       state=present
  with_items:
    - python-cups

- name: Sync CUPS Cloud Print source
  become: yes
  git: repo=https://github.com/simoncadman/CUPS-Cloud-Print.git
       version=20160502
       accept_hostkey=true
       dest=/usr/local/src/cups-cloud-print

- name: Build CUPS Cloud Print
  become: yes
  command: ./configure && make
  args:
    chdir: /usr/local/src/cups-cloud-print
    creates: /usr/local/src/cups-cloud-print/Makefile

- name: Install CUPS Cloud Print
  become: yes
  command: checkinstall
  args:
    chdir: /usr/local/src/cups-cloud-print
    creates: /usr/local/share/cloudprint-cups/setupcloudprint.py
