---
- name: Download go
  become: yes
  unarchive:
    src: https://go.dev/dl/go1.21.4.linux-amd64.tar.gz
    dest: "/usr/local"
    remote_src: yes

- name: Install go tooling
  shell: "go install {{ item.url }}"
  args:
    creates: "{{ ansible_env.HOME }}/.go/pkg/mod/{{ item.path }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/.go"
  with_items:
    - url: github.com/x-motemen/gore/cmd/gore@latest
      path: github.com/x-motemen/gore@*
    - url: github.com/stamblerre/gocode@latest
      path: github.com/stamblerre/gocode@*
    - url: golang.org/x/tools/cmd/godoc@latest
      path: golang.org/x/tools@*/cmd/godoc
    - url: golang.org/x/tools/cmd/goimports@latest
      path: golang.org/x/tools@*/cmd/goimports
    - url: golang.org/x/tools/cmd/gorename@latest
      path: golang.org/x/tools@*/cmd/gorename
    - url: golang.org/x/tools/cmd/guru@latest
      path: golang.org/x/tools@*/cmd/guru
    - url: github.com/cweill/gotests/gotests@latest
      path: github.com/cweill/gotests@*
    - url: github.com/fatih/gomodifytags@latest
      path: github.com/fatih/gomodifytags@*
