---
- name: Clone tfenv
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: "{{ ansible_env.HOME }}/.tfenv"

- name: Symlink tfenv binary
  file:
    state: link
    src: "{{ ansible_env.HOME }}/.tfenv/bin/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
  with_items:
    - terraform
    - tfenv
