---
- name: Add gcloud repo
  become: yes
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud CLI
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install gcloud
  become: yes
  dnf:
    name: google-cloud-cli
