---
- name: Install MySQL
  become: yes
  pacman:
    name: mariadb
    state: present
  register: install_mysql

- name: Install database
  become: yes
  shell: "mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql"
  args:
    executable: /bin/bash
  when: install_mysql.changed

- name: Enable mysql
  become: yes
  systemd:
    name: mariadb
    state: started
    enabled: yes
