---
- name: Sync nvm
  git: repo=https://github.com/creationix/nvm.git
       accept_hostkey=true
       dest=/home/vagrant/.nvm

- name: Install Node.js
  shell: source ~/.nvm/nvm.sh && nvm install v4.2.4
  args:
    executable: /bin/bash

- name: Install tern
  npm: name=tern
       global=yes
       executable=/home/vagrant/.nvm/versions/node/v4.2.4/bin/npm
