---
- name: Remove built-in i3lock
  become: yes
  pacman: name=i3lock
          state=absent
          force=yes

- name: Install i3-related software
  yaourt: name={{item}}
          state=present
  with_items:
    - i3blocks
    - i3lock-custom
    - acpi
    - sysstat
    - unclutter
    - rofi
    - feh
    - gnome-screenshot

- name: Create autologin group
  become: yes
  group: name=autologin
         state=present

- name: Add login user to autologin group
  become: yes
  user: name="{{ansible_env.USER}}"
        groups=autologin
        append=yes

- name: Set i3 as autologin window manager in LightDM
  become: yes
  blockinfile:
    dest: /etc/lightdm/lightdm.conf
    marker: '# {mark} AUTOLOGIN CONFIG'
    block: |
      [SeatDefaults]
      pam-service=lightdm
      pam-autologin-service=lightdm-autologin
      autologin-user={{ansible_env.USER}}
      autologin-user-timeout=0
      session-wrapper=/etc/lightdm/Xsession

- name: Install i3 python library
  become: yes
  pip: name=i3-py
       state=present

- name: Remove system default i3 configs
  file: path={{item}}
        state=absent
  with_items:
    - "{{ansible_env.HOME}}/.i3"
    - "{{ansible_env.HOME}}/.i3status.conf"

- name: Install customized blurlock
  become: yes
  copy: src=blurlock
        dest=/usr/bin/blurlock
