---
- name: Install i3 custom facts
  become: yes
  copy: src=i3.fact
        dest=/etc/ansible/facts.d/i3.fact
        mode=0755

- name: Reload ansible local facts
  setup: filter=ansible_local

- name: Remove built-in i3lock
  become: yes
  pacman: name=i3lock
          state=absent
          force=yes

- name: Install i3-related software
  yaourt: name={{item}}
          state=present
  with_items:
    - cmake
    - i3lock-custom
    - unclutter
    - rofi
    - feh
    - gnome-screenshot

- name: Create autologin group
  become: yes
  group: name=autologin
         state=present

- name: Add login user to autologin group
  become: yes
  user: name="{{ansible_env.USER}}"
        groups=autologin
        append=yes

- name: Set i3 as autologin window manager in LightDM
  become: yes
  blockinfile:
    dest: /etc/lightdm/lightdm.conf
    marker: '# {mark} AUTOLOGIN CONFIG'
    block: |
      [SeatDefaults]
      pam-service=lightdm
      pam-autologin-service=lightdm-autologin
      autologin-user={{ansible_env.USER}}
      autologin-user-timeout=0
      session-wrapper=/etc/lightdm/Xsession

- name: Install i3 python library
  become: yes
  pip: name=i3-py
       state=present

- name: Remove system default i3 configs
  file: path={{item}}
        state=absent
  with_items:
    - "{{ansible_env.HOME}}/.i3"
    - "{{ansible_env.HOME}}/.i3status.conf"

- name: Install customized blurlock
  become: yes
  copy: src=blurlock
        dest=/usr/bin/blurlock

- name: Create systemd service to run screen lock on sleep
  become: yes
  copy:
    src: screenlock@.service
    dest: /usr/lib/systemd/system/screenlock@.service

- name: Enable screen lock service for current user
  become: yes
  file:
    src: /usr/lib/systemd/system/screenlock@.service
    dest: "/etc/systemd/system/sleep.target.wants/screenlock@{{ansible_env.USER}}.service"
    state: link
