---
- name: Install i3 and related software
  become: yes
  apt: name={{item}}
       state=present
  with_items:
    - i3
    - i3blocks
    - compton
    - xautolock
    - pasystray
    - fdpowermon
    - pcmanfm
    - arandr
    - rofi
    - gnome-settings-daemon
    - feh

- name: Set i3 as window manager in LightDM
  become: yes
  lineinfile: dest=/etc/lightdm/lightdm.conf
              line="user-session=i3"

- name: Grant no-password sudo privileges to necessary commands
  become: yes
  lineinfile: dest=/etc/sudoers
              line={{item}}
  with_items:
    - "{{ansible_env.USER}} ALL=(ALL:ALL) NOPASSWD: /sbin/reboot"
    - "{{ansible_env.USER}} ALL=(ALL:ALL) NOPASSWD: /sbin/poweroff"
    - "{{ansible_env.USER}} ALL=(ALL:ALL) NOPASSWD: /usr/bin/setpci"

- name: Uninstall Nautilus
  become: yes
  apt: name=nautilus
       state=absent
  # TODO: set pcmanfm as default: http://askubuntu.com/a/335911
  # https://ask.fedoraproject.org/en/question/37536/how-can-i-set-pcmanfm-file-manager-as-default/?answer=37538#post-id-37538
