---
- name: Install i3 and related software
  become: yes
  apt: name={{item}}
       state=installed
  with_items:
    - i3
    - i3blocks
    - compton
    - thunar
    - arandr
    - rofi
    - gnome-settings-daemon
    - feh

- name: Set i3 as window manager in LightDM
  become: yes
  lineinfile: dest=/etc/lightdm/lightdm.conf
              line="user-session=i3"
