---
- name: Install i3 and related software
  become: yes
  apt: name={{item}}
       state=installed
  with_items:
    - i3
    - i3blocks
    - compton
    - pasystray
    - fdpowermon
    - pcmanfm
    - arandr
    - rofi
    - gnome-settings-daemon
    - feh
    - xclip

- name: Set i3 as window manager in LightDM
  become: yes
  lineinfile: dest=/etc/lightdm/lightdm.conf
              line="user-session=i3"

- name: Grant no-password sudo privileges to necessary commands
  become: yes
  lineinfile: dest=/etc/sudoers
              line={{item}}
  with_items:
    - "{{ansible_env.USER}} ALL=(ALL:ALL) NOPASSWD: /sbin/reboot"
    - "{{ansible_env.USER}} ALL=(ALL:ALL) NOPASSWD: /sbin/poweroff"
    - "{{ansible_env.USER}} ALL=(ALL:ALL) NOPASSWD: /usr/bin/setpci"

- name: Install MFA tool
  become: yes
  copy: src=mfa
        dest=/usr/local/bin/mfa
        mode=0755
