---
- name: Install terminal tooling via Homebrew
  community.general.homebrew:
    name:
      - tmux
      - fzf
      - jq
      - lsd
      - bat
      - age
      - fastfetch
      - htop
      - ncdu
      - fd
      - ripgrep
      - difftastic
      - diceware
      - doggo
      - lf
      - dust
      - zsh
      - step

- name: Install alacritty
  community.general.homebrew_cask:
    name: alacritty

- name: Remove quarantine flag from Alacritty
  ansible.builtin.command: xattr -d com.apple.quarantine /Applications/Alacritty.app
  changed_when: false
  failed_when: false
