---
# Platform-specific packages
- ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == 'Darwin'

# Shared setup
- name: Set up oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Clone powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Clone zsh-users plugins
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/{{ item }}.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item }}"
  with_items:
    - zsh-completions
    - zsh-syntax-highlighting
    - zsh-history-substring-search

- name: Make tmux plugins dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.tmux/plugins"
    state: directory

- name: Install tpm for tmux plugins
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Install tmux plugins via tpm
  ansible.builtin.shell: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"
  changed_when: false

- name: Create local bin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Make lf config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/lf"
    state: directory

- name: Create pv binary (for bat file previews)
  ansible.builtin.copy:
    src: "files/bin/pv"
    dest: "{{ ansible_env.HOME }}/.local/bin/pv"
    mode: +x

- name: Create dropterm launcher
  ansible.builtin.copy:
    src: "files/bin/dropterm"
    dest: "{{ ansible_env.HOME }}/.local/bin/dropterm"
    mode: +x
