---
- name: Remove Pale Moon
  become: yes
  pacman: name=palemoon-bin
          state=absent

- name: Install Firefox Beta and Firefox Developer Edition
  yaourt: name={{item}}
          state=present
  with_items:
    - firefox-beta-bin
    - firefox-developer
