---
- name: Clone Facetime HD camera firmware source
  become: yes
  git: repo=https://github.com/patjak/bcwc_pcie.git
       update=no
       accept_hostkey=true
       dest=/usr/local/src/bcwc_pcie

- name: Extract Facetime HD camera firmware
  become: yes
  command: make
  args:
    chdir: /usr/local/src/bcwc_pcie/firmware
    creates: /usr/local/src/bcwc_pcie/firmware/AppleCameraInterface

- name: Install Facetime HD camera
  become: yes
  command: checkinstall
  args:
    chdir: /usr/local/src/bcwc_pcie/firmware
    creates: /lib/firmware/facetimehd/firmware.bin

- name: Add Facetime HD kernel module PPA
  become: yes
  apt_repository: repo="ppa:psanford/facetimehd"

- name: Install Facetime HD kernel module
  become: yes
  apt: name=facetimehd-dkms
       state=present

- name: Load Facetime HD module on startup
  become: yes
  lineinfile: dest=/etc/modules
              line=facetimehd

- name: Load Facetime HD module after suspend
  become: yes
  copy: src=99facetimehd
        dest=/lib/systemd/system-sleep/99facetimehd
        mode=0755
