---
- name: Create completions directory
  file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/completions"
    state: directory

- name: Ignore completions directory in git
  lineinfile:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/.git/info/exclude"
    line: completions/
    create: yes

- name: Add chezmoi completion
  shell: "chezmoi completion zsh > {{ ansible_env.HOME }}/.oh-my-zsh/completions/_chezmoi"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/completions/_chezmoi"
  register: chezmoi_completion

- name: Remove compinit dump file
  file:
    path: "{{ ansible_env.HOME }}/.zcompdump_completion"
    state: absent
  # when: zsh_completions.changed or completions_plugin.changed
  when: chezmoi_completion.changed
