---
- name: Add docker repo
  become: yes
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
    warn: false

- name: Install docker
  become: yes
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Enable docker service
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started
