[general]
import = ["~/.config/alacritty/dracula.toml"]

[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"

[window]
decorations = "None"
opacity = 0.92
title = "dropterm"
startup_mode = "Maximized"

[window.position]
x = 0
y = 0
