---
- name: Install system basics
  become: yes
  apt: name={{item}}
       state=installed
       update_cache=true
  with_items:
    - build-essential
    - ranger
    - tree
    - htop
    - unzip
