---
- name: Install vim
  become: yes
  dnf:
    name: vim-enhanced

- name: Create themes
  file:
    path: "{{ ansible_env.HOME }}/.vim/pack/themes/start"
    state: directory

- name: Clone dracula theme
  git:
    repo: https://github.com/dracula/vim.git
    dest: "{{ ansible_env.HOME }}/.vim/pack/themes/start/dracula"
