---
# Platform-specific packages
- ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == 'Darwin'

# Shared setup
- name: Create themes directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim/pack/themes/start"
    state: directory

- name: Clone dracula theme
  ansible.builtin.git:
    repo: https://github.com/dracula/vim.git
    dest: "{{ ansible_env.HOME }}/.vim/pack/themes/start/dracula"
