---
- name: Install vim
  become: yes
  apt: name={{item}}
       state=installed
  with_items:
    - vim-nox

- name: Configure basic vimrc
  get_url: url=https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
           dest=/home/vagrant/.vimrc

- name: Create vim colors directory
  file: path=/home/vagrant/.vim/colors
        state=directory

- name: Download solarized color scheme
  get_url: url=https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
           dest=/home/vagrant/.vim/colors/solarized.vim

- name: Configure color scheme
  lineinfile: dest=/home/vagrant/.vimrc
              line={{item}}
  with_items:
    - set t_ut=
    - set background=dark
    - let g:solarized_termcolors=256
    - colorscheme solarized
