---
- name: Remove default Ubuntu directories
  become: yes
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=absent
  with_items:
    - Desktop
    - Documents
    - examples.desktop
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: Create home subdirectories
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=directory
  with_items:
    - Workspaces
    - Dropbox
    - Dropbox/Notes

- name: Symlink ~/Notes to Dropbox notes
  file: src="{{ansible_env.HOME}}/Dropbox/Notes"
        dest="{{ansible_env.HOME}}/Notes"
        state=link
