---
- name: Remove default user directories
  become: yes
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=absent
  with_items:
    - Documents
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: Ensure user directory config exists
  copy: src=user-dirs.dirs
        dest="{{ansible_env.HOME}}/.config/user-dirs.dirs"

- name: Set user directory to use HOME directly
  lineinfile: dest="{{ansible_env.HOME}}/.config/user-dirs.dirs"
              regexp="^{{item}}"
              line="{{item}}=\"$HOME\""
  with_items:
    - XDG_TEMPLATES_DIR
    - XDG_PUBLICSHARE_DIR
    - XDG_DOCUMENTS_DIR
    - XDG_MUSIC_DIR
    - XDG_PICTURES_DIR
    - XDG_VIDEOS_DIR

- name: Ensure Downloads user directory is set
  lineinfile: dest="{{ansible_env.HOME}}/.config/user-dirs.dirs"
              regexp={{item.regexp}}
              line={{item.line}}
  with_items:
    - { regexp: "^XDG_DOWNLOAD_DIR", line: "XDG_DOWNLOAD_DIR=\"$HOME/Downloads\"" }
    - { regexp: "^XDG_DESKTOP_DIR", line: "XDG_DESKTOP_DIR=\"$HOME/Desktop\"" }

- name: Create home subdirectories
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=directory
  with_items:
    - Desktop
    - Downloads
    - Workspaces
