---
- name: Remove default Ubuntu directories
  become: yes
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=absent
  with_items:
    - Desktop
    - Documents
    - examples.desktop
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: Set user directories to use HOME instead
  lineinfile: dest="{{ansible_env.HOME}}/.config/user-dirs.dirs"
              regexp="^{{item}}"
              line="{{item}}=\"$HOME\""
  with_items:
    - XDG_DESKTOP_DIR
    - XDG_TEMPLATES_DIR
    - XDG_PUBLICSHARE_DIR
    - XDG_DOCUMENTS_DIR
    - XDG_MUSIC_DIR
    - XDG_PICTURES_DIR
    - XDG_VIDEOS_DIR

- name: Create home subdirectories
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=directory
  with_items:
    - Workspaces
    - Dropbox
    - Dropbox/Notes

- name: Symlink ~/Notes to Dropbox notes
  file: src="{{ansible_env.HOME}}/Dropbox/Notes"
        dest="{{ansible_env.HOME}}/Notes"
        state=link
