---
- name: Remove default user directories
  become: yes
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=absent
  with_items:
    - Documents
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: Create home subdirectories
  file: path="{{ansible_env.HOME}}/{{item}}"
        state=directory
  with_items:
    - Desktop
    - Downloads
    - Workspaces

- name: Configure user directories
  copy: src=user-dirs.dirs
        dest="{{ansible_env.HOME}}/.config/user-dirs.dirs"

- name: Remove deprecated mimeapps.list
  file:
    path: "{{ansible_env.HOME}}/.local/share/applications/mimeapps.list"
    state: absent

- name: Configure defaults
  copy:
    src: mimeapps.list
    dest: "{{ansible_env.HOME}}/.config/mimeapps.list"
