---
- name: Remove urxvt, xterm, and vte3
  become: yes
  pacman: name={{item}}
          state=absent
          force=yes
  with_items:
    - rxvt-unicode
    - xterm
    - vte3

- name: Install vte3-ng
  become: yes
  pacman: name=vte3-ng
          state=present

- name: Install termite
  yaourt: name=termite
          state=present
