---
- name: Remove vte3
  become: yes
  pacman: name=vte3
          state=absent
          force=yes
  with_items:
    - vte3

- name: Install vte3-ng and termite
  become: yes
  pacman: name={{item}}
          state=present
  with_items:
    - vte3-ng
    - termite
