---
- name: Install Plymouth for graphical boot
  become: yes
  pacman: name=plymouth
          state=present

- name: Configure plymouth in mkinitcpio
  become: yes
  lineinfile:
    dest: /etc/mkinitcpio.conf
    regexp: "^HOOKS=\"base udev (.*) encrypt (.*)$"
    line: 'HOOKS="base udev plymouth \1 plymouth-encrypt \2'
    backrefs: yes
  register: configure_mkinitcpio

- name: Symlink necessary Infinality font files
  become: yes
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  with_items:
    - { src: "/usr/share/fonts/ttf-dejavu-ib/DejaVuSans.ttf", dest: "/usr/share/fonts/TTF/DejaVuSans.ttf" }
    - { src: "/etc/fonts/conf.d/60-latin-free.conf", dest: "/etc/fonts/conf.d/60-latin.conf" }
  register: symlink_fonts

- name: Rebuild initrd image
  become: yes
  command: "{{item}}"
  with_items:
    - "mkinitcpio -p linux310"
    - "mkinitcpio -p linux44"
  when: configure_mkinitcpio|changed or symlink_fonts|changed

- name: Configure GRUB kernel command line parameters
  become: yes
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=\"quiet (?!splash)(.*)$"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash \1'
    backrefs: yes
  register: configure_kernel

- name: Re-generate GRUB configuration
  become: yes
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: configure_kernel|changed
