---
- name: Install Arc GTK theme
  yaourt: name=gtk-theme-arc-git
          state=present

- name: Set GTK theme to Arc-Darker
  lineinfile: dest="{{ansible_env.HOME}}/.gtkrc-2.0"
              regexp="^gtk-theme-name="
              line="gtk-theme-name=\"Arc-Darker\""
              create=yes
