---
- name: Add Arc GTK theme apt repository
  become: yes
  apt_repository: repo="deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /"
                  state=present
  
- name: Install Arc GTK theme
  become: yes
  apt: name=arc-theme
       state=present
       allow_unauthenticated=yes

- name: Set GTK theme to Arc-Darker
  command: gsettings set org.gnome.desktop.interface gtk-theme "Arc-Darker"
