---
- name: Sync nvm
  git: repo=https://github.com/creationix/nvm.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.nvm"

- name: Install Node.js
  shell: "source {{ansible_env.HOME}}/.nvm/nvm.sh && nvm install v4.2.4"
  args:
    executable: /bin/bash
    creates: "{{ansible_env.HOME}}/.nvm/versions/node/v4.2.4/bin/node"

- name: Install tern
  npm: name=tern
       global=yes
       executable="{{ansible_env.HOME}}/.nvm/versions/node/v4.2.4/bin/npm"
