---
- name: Install node custom facts
  become: yes
  copy: src=node.fact
        dest=/etc/ansible/facts.d/node.fact
        mode=0755

- name: Reload ansible local facts
  setup: filter=ansible_local

- name: Sync nvm
  git: repo=https://github.com/creationix/nvm.git
       accept_hostkey=true
       dest="{{ansible_env.HOME}}/.nvm"

- name: Install Node.js (LTS)
  shell: "source {{ansible_env.HOME}}/.nvm/nvm.sh && nvm install --lts"
  args:
    executable: /bin/bash
    creates: "{{ansible_env.HOME}}/.nvm/versions/node/*/bin/node"

- name: Set LTS version as default
  shell: "source {{ansible_env.HOME}}/.nvm/nvm.sh && nvm alias default lts/*"
  args:
    executable: /bin/bash
  when: not ansible_local.node.default_version

- name: Reload ansible local facts
  setup: filter=ansible_local

- name: Install common node tools
  shell: "source {{ansible_env.HOME}}/.nvm/nvm.sh && nvm use --lts && npm install -g {{item}}"
  args:
    executable: /bin/bash
    creates: "{{ansible_env.HOME}}/.nvm/versions/node/{{ansible_local.node.default_version}}/bin/{{item}}"
  with_items:
    - yarn
    - tern
    - js-beautify
    - eslint
    - babel-eslint
    - eslint-plugin-react
    - gulp
    - yo
    - create-react-app
    - pushstate-server
    - vmd
    - "@storybook/cli"
